apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: drift-detection
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minio"
  AWS_SECRET_ACCESS_KEY: "minio123"
  MINIO_ROOT_USER: "minio"
  MINIO_ROOT_PASSWORD: "minio123"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: drift-detection
type: Opaque
stringData:
  POSTGRES_USER: "airflow"
  POSTGRES_PASSWORD: "airflow"
  POSTGRES_DB: "airflow"
  AIRFLOW_CONN: "postgresql+psycopg2://airflow:airflow@postgres.drift-detection.svc.cluster.local:5432/airflow"
